//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActiveCampaign.Tests.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Files {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Files() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ActiveCampaign.Tests.Resources.Files", typeof(Files).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] address_list {
            get {
                object obj = ResourceManager.GetObject("address_list", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///
        ///&lt;subscriber_sync&gt;
        ///
        ///&lt;result_code&gt;0&lt;/result_code&gt;
        ///
        ///&lt;result_message&gt;There was an error processing custom field CompanyName. Try encoding each &apos;field[]&apos; parameter.&lt;/result_message&gt;
        ///
        ///&lt;result_output&gt;xml&lt;/result_output&gt;
        ///
        ///&lt;/subscriber_sync&gt;.
        /// </summary>
        internal static string subs_sync {
            get {
                return ResourceManager.GetString("subs_sync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///
        ///&lt;subscriber_insert_post&gt;
        ///
        ///&lt;subscriber_id&gt;154&lt;/subscriber_id&gt;
        ///
        ///&lt;sendlast_should&gt;0&lt;/sendlast_should&gt;
        ///
        ///&lt;sendlast_did&gt;0&lt;/sendlast_did&gt;
        ///
        ///&lt;result_code&gt;1&lt;/result_code&gt;
        ///
        ///&lt;result_message&gt;Contact added&lt;/result_message&gt;
        ///
        ///&lt;result_output&gt;xml&lt;/result_output&gt;
        ///
        ///&lt;/subscriber_insert_post&gt;.
        /// </summary>
        internal static string subscriber_insert_post {
            get {
                return ResourceManager.GetString("subscriber_insert_post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos; encoding=&apos;utf-8&apos;?&gt;
        ///&lt;subscriber_update_post&gt;&lt;result_code&gt;0&lt;/result_code&gt;&lt;result_message&gt;You did not select any lists.&lt;/result_message&gt;&lt;result_output&gt;xml&lt;/result_output&gt;&lt;/subscriber_update_post&gt;.
        /// </summary>
        internal static string subscriber_update_post {
            get {
                return ResourceManager.GetString("subscriber_update_post", resourceCulture);
            }
        }
    }
}
